#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_abc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver


  #mvc拦截器配置
  mvc:
    view:
      prefix: /
      suffix: .html

  #kafka配置
  kafka:
    # kafka服务地址
    bootstrap-servers: 192.168.10.100:9092
    # 消费者配置
    consumer:
      bootstrap-servers: 192.168.10.100:9092
      group-id: myGroup
      enable-auto-commit: true
      auto-offset-reset: earliest
      auto-commit-interval: 1000
      max-poll-records: 10
    # 生产者配置
    producer:
      retries: 5
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1






#mybatisplus配置
mybatis-plus:
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      id-type: auto
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

